### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by richardhj** [1up-lab/contao-sentry-bundle#1]
Hi!

Thank you a lot for updating the extension.

I aimed to implement the user feedback. This is how I did it:

src/Resources/config/listeners.yml
```yml
services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }

    app.twig_runtime:
        class: AppBundle\Twig\AppRuntime
        public: false
        arguments: ['@sentry.client']
        tags:
            - { name: twig.runtime }
```

src/Twig/AppExtension.php
```php
<?php

namespace AppBundle\Twig;

class AppExtension extends \Twig_Extension
{
    public function getFilters(): array
    {
        return [
            new \Twig_SimpleFilter('sentry_last_event_id', [AppRuntime::class, 'sentryLastEventIdFilter']),
        ];
    }
}
```

src/Twig/AppRuntime.php
```php
<?php

namespace AppBundle\Twig;


class AppRuntime
{
    /**
     * @var \Raven_Client
     */
    private $client;

    /**
     * AppRuntime constructor.
     *
     * @param \Raven_Client $client
     */
    public function __construct(\Raven_Client $client)
    {
        $this->client = $client;
    }

    public function sentryLastEventIdFilter(): ?string
    {
        return $this->client->getLastEventID();
    }
}

```

Copy of the `CoreBundle/views/Error/layout.html.twig`
app/Resources/ContaoCoreBundle/views/Error/layout.html.twig
```twig
    <!-- Sentry JS SDK 2.1.+ required -->
    <script src="https://cdn.ravenjs.com/3.23.1/raven.min.js"></script>

    {%  set sentry_id = ''|sentry_last_event_id %}
    {% if sentry_id %}
        <script>
            Raven.showReportDialog({
                // grab the eventId generated by the Sentry SDK
                eventId: '{{ sentry_id }}',

                // use the public DSN (dont include your secret!)
                dsn: 'https://123456789@sentry.io/211233'
            });
        </script>
    {% endif %}
</body>
</html>
```

Currently, this is on an app-basis.
What do you think about this approach?
Do you want to add the twig extension to this package? Or should it rather be implemented in the sentry/sentry-symfony package? Or nothing at all?
Within Contao, the error templates are prepared in the `PrettyErrorScreenListener` which gives no way to modify the template.

![screen shot 2018-06-22 at 16 30 39](https://user-images.githubusercontent.com/1284725/41782120-a06637f0-7639-11e8-96d7-a053e7ddd232.png)
